export const allProduct = {
  FETCH_ALL_PRODUCT_REQUEST: 'FETCH_ALL_PRODUCT_REQUEST',
  FETCH_ALL_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_SUCCESS',
  FETCH_ALL_PRODUCT_FAILURE: 'FETCH_ALL_PRODUCT_FAILURE',
  ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
};

export const myProducts = {
  FETCH_MY_PRODUCT_REQUEST: 'FETCH_MY_PRODUCT_REQUEST',
  FETCH_MY_PRODUCT_SUCCESS: 'FETCH_MY_PRODUCT_SUCCESS',
  FETCH_MY_PRODUCT_FAILURE: 'FETCH_MY_PRODUCT_FAILURE',
  ADD_MYPRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  EDIT_MYPRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
  DELETE_MYPRODUCT: 'DELETE_PRODUCT',
};

export const Login = {
  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  LOGOUT: 'LOGOUT',
};


export const userProfile = {
  MY_PROFILE_REQUEST:'MY_PROFILE_REQUEST',
  MY_PROFILE_SUCCESS:'MY_PROFILE_SUCCESS',
  MY_PROFILE_FAILED:'MY_PROFILE_FAILED',
}

export const Register = {
  REGISTER_REQUEST:'REGISTER_REQUEST',
  REGISTER_SUCCESS:'REGISTER_SUCCESS',
  REGISTER_FAILED:'REGISTER_FAILED',
}
