export const MY_PRODUCT_REQUEST = 'MY_PRODUCT_REQUEST';
export const MY_PRODUCT_SUCCESS = 'MY_PRODUCT_SUCCESS';
export const MY_PRODUCT_FAILED = 'MY_PRODUCT_FAILED';
export const MY_PRODUCT_DELETE= 'MY_PRODUCT_DELETE';